### ISSUE TITLE
GOLD MINE

### ISSUE THREAD

**Issue by gingerbeardman** [uncletrunks/missingpiece#11]
[Archived homepage](https://web.archive.org/web/20021006224220fw_/http://wakatsukido.tripod.co.jp/pceapp/index.html
)
Developer: Wakatsukido!

Status: lost

![image](https://user-images.githubusercontent.com/49612/132891254-8a625620-225c-45d0-b070-414e5bb934ff.gif)
![image](https://user-images.githubusercontent.com/49612/132891258-0d930d00-5826-4c7b-acaf-4271fe538ea8.gif)
![image](https://user-images.githubusercontent.com/49612/132891263-d195caa5-0fb0-4191-ac19-a2e649ac9793.gif)

**Comment by gingerbeardman** [comment]
This is on P/ECE Hand Book Vol 1 CD

**Comment by uncletrunks** [comment]
On their current website:
http://wakatsukido.net/pceapp/index.html
