### ISSUE TITLE
Chūka musume to asobou! !

### ISSUE THREAD

**Issue by gingerbeardman** [uncletrunks/missingpiece#12]
[Archived homepage](https://web.archive.org/web/20021006224220fw_/http://wakatsukido.tripod.co.jp/pceapp/index.html
)
Developer: Wakatsukido!

Status: lost

AKA:
- 中華娘と遊ぼう!! 
- Let's play with a Chinese girl !!

![image](https://user-images.githubusercontent.com/49612/132891414-5592d511-7352-4ca1-b4b0-bb5a35f9996d.gif)
![image](https://user-images.githubusercontent.com/49612/132891420-5ed3a009-084d-4da8-928c-173664af6912.gif)
![image](https://user-images.githubusercontent.com/49612/132891424-619e8b9a-af56-4bad-9872-636462ec73ea.gif)

**Comment by gingerbeardman** [comment]
This is on P/ECE Hand Book Vol 1 CD

**Comment by uncletrunks** [comment]
Found their current website:
http://wakatsukido.net/pceapp/index.html
