### ISSUE TITLE
PocketTuner

### ISSUE THREAD

**Issue by gingerbeardman** [uncletrunks/missingpiece#13]
[Archived homepage](https://web.archive.org/web/20021006224220fw_/http://wakatsukido.tripod.co.jp/pceapp/index.html
)
Developer: Wakatsukido!

Status: lost

![image](https://user-images.githubusercontent.com/49612/132891547-f7891373-3afc-4b16-b639-b81a5c335e07.gif)

**Comment by gingerbeardman** [comment]
This is on P/ECE Hand Book Vol 1 CD

**Comment by uncletrunks** [comment]
Available on current website:
http://wakatsukido.net/pceapp/index.html
