### ISSUE TITLE
Black or Light!

### ISSUE THREAD

**Issue by gingerbeardman** [uncletrunks/missingpiece#14]
[Archived homepage](https://web.archive.org/web/20021006224220fw_/http://wakatsukido.tripod.co.jp/pceapp/index.html
)
Developer: Wakatsukido!

Status: lost

![image](https://user-images.githubusercontent.com/49612/132891578-eccf7764-a6d9-45a6-8cc4-00d0ccb05958.gif)
![image](https://user-images.githubusercontent.com/49612/132891582-991d074a-a749-4e9a-ab14-06ee37dd7cd7.gif)

**Comment by uncletrunks** [comment]
Available on current website:
http://wakatsukido.net/pceapp/index.html
