### ISSUE TITLE
Gravity - Prototype -

### ISSUE THREAD

**Issue by gingerbeardman** [uncletrunks/missingpiece#15]
[Archived homepage](https://web.archive.org/web/20021006224220fw_/http://wakatsukido.tripod.co.jp/pceapp/index.html
)
Developer: Wakatsukido!

Status: lost

AKA
- Gravity - 試作版 -

![image](https://user-images.githubusercontent.com/49612/132891624-41bd2693-a35b-4c4b-90a8-afbc9b3fcb87.gif)
![image](https://user-images.githubusercontent.com/49612/132891630-616e7a8b-c2d1-484d-ac2f-97dc1caf3961.gif)

**Comment by uncletrunks** [comment]
Not linked to, but still hosted on their server at
https://wakatsukido.net/pceapp/gravity/gravity.lzh

**Comment by gingerbeardman** [comment]
Nice work!
