### ISSUE TITLE
Shideshajin

### ISSUE THREAD

**Issue by uncletrunks** [uncletrunks/missingpiece#16]
No Homepage
Developer: Golzy 
Known Filename: gs_shide.lzh

Screenshot:
![image](https://user-images.githubusercontent.com/51267277/132934751-d4c0a142-f927-4bca-8f44-26a10a617010.png)

The name comes from a plant named for its resemblance to [shide](https://en.wikipedia.org/wiki/Shide_(Shinto)), a type of streamer used in Shinto. This is keeping with the Shinto theme of Golzy's other game, Hamaemashi Norito (where you play as a votive picture and exorcise youkai).

**Comment by zurachu** [comment]
I uploaded unofficial contest "P-Kon 2004" website!
https://zurachu.github.io/old_zurachu_net/pkon2004/result.html
