### ISSUE TITLE
Infinity Gem

### ISSUE THREAD

**Issue by uncletrunks** [uncletrunks/missingpiece#5]
[Archived Homepage](https://web.archive.org/web/20060822032517/http://hawzel.plala.jp/piece.htm)
Developer: Angel Knight

Screenshots:
![image](https://user-images.githubusercontent.com/51267277/132748141-a89505fd-d269-4213-b299-f7a3652bc42a.png)

**Comment by gingerbeardman** [comment]
Known filename: `infgem.zip`

**Comment by uncletrunks** [comment]
Included in Zurachu's reupload of P-Kon 2004 files.
https://zurachu.github.io/old_zurachu_net/pkon2004/result.html
