### ISSUE TITLE
GenShell

### ISSUE THREAD

**Issue by uncletrunks** [uncletrunks/missingpiece#6]
[Archived Homepage](https://web.archive.org/web/20131112204256/http://www13.plala.or.jp/genge/)
Developer: Genge

Screenshots:
![image](https://user-images.githubusercontent.com/51267277/132748869-5bc62eb4-718e-4994-963e-7b0d84732427.png)
![image](https://user-images.githubusercontent.com/51267277/132748882-2a0b7426-756e-4521-824c-85759d5a09dc.png)
![image](https://user-images.githubusercontent.com/51267277/132748889-ad655175-c6e9-42a0-a6b9-7cb2075d88dc.png)
![image](https://user-images.githubusercontent.com/51267277/132748906-22b11aed-7ce0-4292-a52a-5f6c56202cad.png)
![image](https://user-images.githubusercontent.com/51267277/132748924-a94afba9-2dfb-4690-a201-4294b37cca5a.png)
![image](https://user-images.githubusercontent.com/51267277/132748930-5791561d-b600-4dab-8d15-068287a7a0b2.png)
![image](https://user-images.githubusercontent.com/51267277/132748963-769749f4-5484-47f2-99b6-6f53a3d5a019.png)
![image](https://user-images.githubusercontent.com/51267277/132748982-279bfc32-f2b4-4aff-8dec-d6ce4819e644.png)
![image](https://user-images.githubusercontent.com/51267277/132748997-9fc3b662-fba7-4d61-ad1b-57ce038bb1f0.png)
![image](https://user-images.githubusercontent.com/51267277/132749008-1579a6d6-765c-4f0c-9173-5311e30e5bf6.png)
![image](https://user-images.githubusercontent.com/51267277/132749028-81a043db-667a-483b-85fb-00ca7ebb4586.png)
![image](https://user-images.githubusercontent.com/51267277/132749045-830b1e20-6df2-470b-81fa-aa3f39199705.png)

Robust alternative system software.

**Comment by gingerbeardman** [comment]
Known filename: `genshell.lzh`

**Comment by zurachu** [comment]
I uploaded unofficial contest "P-Kon" website!
https://zurachu.github.io/old_zurachu_net/pkon/result.html
