### ISSUE TITLE
TIDE for P/ECE

### ISSUE THREAD

**Issue by uncletrunks** [uncletrunks/missingpiece#8]
[Archived Homepage](https://web.archive.org/web/20040815003529/http://pro.tok2.com/~hirock/Software/TidePiece/index.html)
Developer: hirock

Screenshot:
![image](https://user-images.githubusercontent.com/51267277/132788245-8f81d2b5-97d5-400d-ab91-09b09de3f175.png)
![image](https://user-images.githubusercontent.com/51267277/132788254-075381cf-f515-4cd2-a3b5-c9b37a97cfc8.png)

Tide calculator.

**Comment by gingerbeardman** [comment]
This is on P/ECE Hand Book Vol 1 CD
